version: 2.4.1.{build}

branches:
  only:
  - develop

image:
  - Visual Studio 2013
#  - Visual Studio 2015

shallow_clone: true # clone the last commit without history

environment:
  MSBUILD_FLAGS: /verbosity:normal /maxcpucount
  matrix:
#  - QT5: C:\Qt\5.9\msvc2015
#    CMAKE_GENERATOR: Visual Studio 14 2015
#    CONFIGURATION: Release
#    VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
#    VC_VARS_ARCH: x86
##    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - QT5: C:\Qt\5.9\msvc2015_64
#    CMAKE_GENERATOR: Visual Studio 14 2015 Win64
#    CONFIGURATION: Release
#    VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
#    VC_VARS_ARCH: amd64
  - QT5: C:\Qt\5.6\msvc2013
    CMAKE_GENERATOR: Visual Studio 12 2013
    CONFIGURATION: Release
    VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\
    VC_VARS_ARCH: x86

install:
- cmd: >-
    set Qt5_DIR=%QT5%\lib\cmake\Qt5
    set Path=%QT5%\bin;%Path%

build_script:
- cmd: >-
    cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%" "-DCMAKE_BUILD_TYPE=%CONFIGURATION%"
    cmake --build build --config %CONFIGURATION% -- %MSBUILD_FLAGS%
    cd build
    cpack -C %CONFIGURATION% -G ZIP
    cpack -C %CONFIGURATION% -G NSIS
    cd ..

artifacts:
- path: build/qstopmotion-*.zip
  name: portable
- path: build/qstopmotion-*.exe
  name: installer
