.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH STOPMOTION 1 "May 25th, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
qStopMotion \- a program for creating stop-motion animations
.SH SYNOPSIS
.B qStopMotion
.I file
.br
.SH DESCRIPTION
This manual page briefly introduces the program and documents the commands
available when running in non GUI mode.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBqStopMotion\fP is a program for creating stop-motions animations from
couple of images. You can use your favourite video device for grabbing
the images as long you have a program capable of doing it. You just sets
qStopMotion to use the program. It's also possible to do the same with 
video export. Stopmotion has a set of tools which helps you creating the 
movements smooth and precise.
.SH OPTIONS
Stopmotion follows the usual GNU command line syntax, with long
options starting with two dashes (`-'). This part of the program is
under construction and not yet fully usable.
A summary of options is included below.
.TP
.B \-a DIR, \-\-addFrames=DIR
Creates a new project containing the images located in DIR (e.g. /foo/bar)
.SH SEE ALSO
The full documentation for qStopMotion is maintained in the application help menu. 
Visit the projects website for more informations. 
(http://www.qStopMotion.org)
.br
.SH AUTHORS
qStopMotion is written by Ralf Lange and a fork of stopmotion for Linux
written by Bjoern Erik Nilsen and Fredrik Berg Kjoelstad.
.SH REPORTING BUGS
Report bugs to <ralf.lange@qstopmotion.org>.
.PP
This manual page was written by Ralf Lange and Bjoern Erik Nilsen.

